In [1]:
import numpy as np
import json
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
data_point = '0050'
npy_file_path = f'/home/digi2/colino_dir/gen_data_ground_truth/figure8_transporter_empty-30fps_800frames-rec1/bounding_box_3d_{data_point}.npy'
labels_file_path = f'/home/digi2/colino_dir/gen_data_ground_truth/figure8_transporter_empty-30fps_800frames-rec1/bounding_box_3d_labels_{data_point}.json'
data_npy = np.load(npy_file_path, allow_pickle=True)

In [3]:
print("Contents of the .npy file:")
print(data_npy[:])

Contents of the .npy file:
[(0, -103.332886, -40.866943 , -4.9675827 , 39.759827, 24.295105 , 14.706866, [[ 8.5040126e-03,  5.2613425e-03, -6.1885639e-06,  0.0000000e+00], [-5.2613313e-03,  8.5039949e-03,  4.7342454e-09,  0.0000000e+00], [ 5.2652422e-06,  3.2519824e-06,  9.9999746e-03,  0.0000000e+00], [-8.7780991e+00,  1.2696862e+00,  8.0001205e-02,  1.0000000e+00]], 0.3078    )
 (0,   -8.107727,  -2.7095337, -8.106529  ,  8.106689,  3.0150146,  8.107843, [[ 8.5034035e-03,  5.2617965e-03,  7.4973497e-05,  0.0000000e+00], [-5.2619320e-03,  8.5036233e-03,  4.0236245e-09,  0.0000000e+00], [-6.3752515e-05, -3.9453964e-05,  9.9996952e-03,  0.0000000e+00], [-8.8859873e+00,  1.4440343e+00,  7.9999790e-02,  1.0000000e+00]], 0.0219    )
 (0,   -8.107544,  -3.0230103, -8.106494  ,  8.106812,  2.7091675,  8.107803, [[ 8.5028661e-03,  5.2614687e-03,  1.3493927e-04,  0.0000000e+00], [-5.2619260e-03,  8.5036056e-03,  3.9880508e-09,  0.0000000e+00], [-1.1474494e-04, -7.1007438e-05,  9.9990480e-03,  

In [4]:
# Extract the first column
first_elements = [row[0] for row in data_npy]

# Count unique values in the first column
unique_values, counts = np.unique(first_elements, return_counts=True)

In [5]:
print(unique_values, counts)

[0 1] [4 2]


In [6]:
with open(labels_file_path, 'r') as labels_file:
    labels_data = json.load(labels_file)

In [7]:
print("Contents of the label file")
print(labels_data)

Contents of the label file
{'0': {'class': 'transporter1_mesh'}, '1': {'class': 'swetfloorsign'}}


In [8]:
data_npy_full = [list(row) for row in data_npy]

In [9]:
sign_data = [row for row in data_npy_full if row[0] in [1]]

In [10]:
geometries = []

In [11]:
sign_points = []
sign_transforms = []
for row in sign_data:
    x_min = row[1]
    y_min = row[2]
    x_max = row[3]
    y_max = row[4]
    z_min = row[5]
    z_max = row[6]
    
    bbox_points = [
        [x_min, y_min, z_min],
        [x_min, y_min, z_max],
        [x_min, y_max, z_min],
        [x_min, y_max, z_max],
        [x_max, y_min, z_min],
        [x_max, y_min, z_max],
        [x_max, y_max, z_min],
        [x_max, y_max, z_max]
    ]
    
    sign_points.append(bbox_points)
    
    transform = row[7]
    sign_transforms.append(transform.T)
    
    
sign_points = np.array(sign_points).astype(np.float64)
sign_transforms = np.array(sign_transforms).astype(np.float64)   
    
print(sign_points)
print(sign_transforms)

[[[-1.33494873e+01 -1.16166687e+01  1.16166382e+01]
  [-1.33494873e+01 -1.16166687e+01  6.44860077e+01]
  [-1.33494873e+01  1.33494263e+01  1.16166382e+01]
  [-1.33494873e+01  1.33494263e+01  6.44860077e+01]
  [ 4.86281179e-02 -1.16166687e+01  1.16166382e+01]
  [ 4.86281179e-02 -1.16166687e+01  6.44860077e+01]
  [ 4.86281179e-02  1.33494263e+01  1.16166382e+01]
  [ 4.86281179e-02  1.33494263e+01  6.44860077e+01]]

 [[-1.33494329e+01 -1.16168213e+01  1.16165771e+01]
  [-1.33494329e+01 -1.16168213e+01  6.44860077e+01]
  [-1.33494329e+01  1.33494377e+01  1.16165771e+01]
  [-1.33494329e+01  1.33494377e+01  6.44860077e+01]
  [ 4.86281179e-02 -1.16168213e+01  1.16165771e+01]
  [ 4.86281179e-02 -1.16168213e+01  6.44860077e+01]
  [ 4.86281179e-02  1.33494377e+01  1.16165771e+01]
  [ 4.86281179e-02  1.33494377e+01  6.44860077e+01]]]
[[[ 9.32278205e-03 -3.61742149e-03  0.00000000e+00 -7.29774427e+00]
  [ 3.61742149e-03  9.32278205e-03  0.00000000e+00  2.74796438e+00]
  [ 0.00000000e+00  0.000000

In [12]:
sign_pcds = []

for i, row in enumerate(sign_points):
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(row)
    pcd.transform(sign_transforms[i])
    sign_pcds.append(pcd)
    
geometries += sign_pcds

In [13]:
sign_bboxes = []

for i, pcd in enumerate(sign_pcds):
    sign_bbox = pcd.get_oriented_bounding_box()
    sign_bbox.color = [1,0,0]
    sign_bboxes.append(sign_bbox)
    
geometries += sign_bboxes

In [14]:
transporter_points = o3d.utility.Vector3dVector()
transporter_data = [row for row in data_npy_full if row[0] in [0]]

for row in transporter_data:
    x_min = row[1]
    y_min = row[2]
    x_max = row[3]
    y_max = row[4]
    z_min = row[5]
    z_max = row[6]
    
    points = [
        [x_min, y_min, z_min],
        [x_min, y_min, z_max],
        [x_min, y_max, z_min],
        [x_min, y_max, z_max],
        [x_max, y_min, z_min],
        [x_max, y_min, z_max],
        [x_max, y_max, z_min],
        [x_max, y_max, z_max]
    ]
    
    transform = row[7].T

    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(np.array(points).astype(np.float64))
    pcd.transform(np.array(transform).astype(np.float64))
    transporter_points.extend(pcd.points)
    
transporter_pcd = o3d.geometry.PointCloud()
transporter_pcd.points = transporter_points

geometries += [transporter_pcd]

In [15]:
transporter_bbox = transporter_pcd.get_oriented_bounding_box()
transporter_bbox.color = [1,0,0]
geometries += [transporter_bbox]

In [16]:
origin_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=[0, 0, 0])
geometries += [origin_frame]
#geometries = sign_pcds

In [17]:
o3d.visualization.draw_geometries(geometries)